#!/bin/bash

# Smart Downloads Cleanup Script
# Generated by Kiva using GPT-5.3-Codex

echo "🧹 SMART DOWNLOADS CLEANUP"
echo "Current Downloads size: $(du -sh ~/Downloads | cut -f1)"
echo ""

# Create backup directory on external drive if available
BACKUP_DIR="/Volumes/X10 Pro/Downloads-Backup-$(date +%Y%m%d)"
if [ -d "/Volumes/X10 Pro" ]; then
    echo "📦 Creating backup directory: $BACKUP_DIR"
    mkdir -p "$BACKUP_DIR" 2>/dev/null
fi

cd ~/Downloads

echo "🔍 ANALYZING LARGE FILES..."
echo ""

# Function to move large files to backup and show savings
move_to_backup() {
    local pattern="$1"
    local description="$2"
    
    files=($(find . -name "$pattern" -type f 2>/dev/null))
    if [ ${#files[@]} -gt 0 ]; then
        local total_size=$(find . -name "$pattern" -type f -exec du -ch {} + 2>/dev/null | tail -1 | cut -f1)
        echo "📂 $description: ${#files[@]} files, $total_size"
        
        if [ -d "$BACKUP_DIR" ]; then
            echo "   Moving to backup..."
            find . -name "$pattern" -type f -exec mv {} "$BACKUP_DIR/" \; 2>/dev/null
        else
            echo "   ⚠️  No backup drive available. Use: rm -f $pattern"
        fi
        echo ""
    fi
}

# Function to remove files directly
remove_files() {
    local pattern="$1"
    local description="$2"
    
    files=($(find . -name "$pattern" -type f 2>/dev/null))
    if [ ${#files[@]} -gt 0 ]; then
        local total_size=$(find . -name "$pattern" -type f -exec du -ch {} + 2>/dev/null | tail -1 | cut -f1)
        echo "🗑️  $description: ${#files[@]} files, $total_size"
        echo "   Removing..."
        find . -name "$pattern" -type f -delete 2>/dev/null
        echo ""
    fi
}

# 1. Software installers (safe to remove after installation)
echo "🔧 SOFTWARE INSTALLERS:"
remove_files "*.dmg" "DMG installers"
remove_files "*.pkg" "PKG installers"  
remove_files "*.zip" "ZIP installers (check first)"

echo "📹 VIDEO COURSES (backing up to X10 Pro if available):"
# Justin Goff courses
move_to_backup "*Justin Goff*" "Justin Goff courses"
move_to_backup "*Rob Lennon*" "Rob Lennon courses"
move_to_backup "*Ben Adkins*" "Ben Adkins courses"
move_to_backup "*Jake Tran*" "Jake Tran courses"
move_to_backup "*Taylor Lane*" "Taylor Lane courses"
move_to_backup "*Michael Katz*" "Michael Katz courses"

echo "📱 LARGE VIDEOS (backing up to X10 Pro):"
# Large video files (>500MB)
find . -name "*.mp4" -o -name "*.MOV" -o -name "*.mov" -size +500M | while read file; do
    if [ -d "$BACKUP_DIR" ]; then
        echo "   📹 Moving: $(basename "$file") ($(du -sh "$file" | cut -f1))"
        mv "$file" "$BACKUP_DIR/"
    else
        echo "   📹 Large file: $file ($(du -sh "$file" | cut -f1))"
    fi
done

echo "🎵 AUDIO FILES:"
move_to_backup "*.mp3" "Audio files"

echo "📚 EBOOKS/PDFs:"
move_to_backup "*.pdf" "PDF files"
move_to_backup "*.epub" "EPUB files"

echo ""
echo "✅ CLEANUP COMPLETE!"
echo "New Downloads size: $(du -sh ~/Downloads | cut -f1)"

if [ -d "$BACKUP_DIR" ]; then
    echo "📦 Backup location: $BACKUP_DIR"
    echo "💡 Review backed up files and delete from backup if not needed"
fi

echo ""
echo "🚀 RECOMMENDED NEXT STEPS:"
echo "1. Empty Trash to reclaim disk space"
echo "2. Run: xcrun simctl delete all (clear iOS simulators)"  
echo "3. Clear browser caches"
echo "4. Check ~/Library/Developer for Xcode cache"